Repository openshift/release-tests, pull requests merged in 2023-08, with the labels that each got.

#76 refine notification message for must verify bug
  oar/README.md
  oar/core/notification_mgr.py
Labels: lgtm, approved

#74 Update READEME for auto merging test
  README.md
Labels: lgtm, approved

#78 Add doc and prodsec approval basic function
  oar/core/advisory_mgr.py
  tests/test_advisory_mgr.py
Labels: lgtm, approved

#81 add a Dockerfile for k8sgpt
  prow/Dockerfile.k8sgpt
Labels: approved

#84 update k8sgtp dockerfile
  prow/Dockerfile.k8sgpt
Labels: lgtm, approved

#85 make email as required option for cmd take-ownership
  oar/cli/cmd_take_ownership.py
  oar/core/config_store.json
Labels: approved

#86 add slack message receiver
  tools/slack_message_receiver.py
Labels: approved

#87 fix infinite msg error for slack message receiver
  tools/slack_message_receiver.py
Labels: approved

#88 address kubeconfig issue
  prow/Dockerfile.k8sgpt
Labels: approved

#89 Update README.md with bugzilla login api-key
  oar/README.md
Labels: approved

#90 OCPQE-16444 Add workflow when job is in queue
  oar/cli/cmd_image_consistency_check.py
  oar/cli/cmd_stage_testing.py
  oar/core/jenkins_helper.py
Labels: lgtm

#93 refine config store logging
  oar/core/config_store.py
Labels: approved
