Repository openshift/release-tests, pull requests merged in 2023-10, with the labels that each got.

#100 add missed argument for call stage pipeline job
  oar/core/jenkins_helper.py
Labels: lgtm, approved

#102 OCPQE-17313 add func to check dependent advisories
  oar/core/advisory_mgr.py
  tests/test_advisory_mgr.py
Labels: lgtm, approved

#103 OCPQE-17241 Add condition for DROPPED_NO_SHIP ad state
  oar/core/advisory_mgr.py
  oar/core/const.py
  tests/test_advisory_mgr.py
Labels: lgtm, approved

#104 OCPQE-17600: infer the corresponding amd64 build based on the provided arm build
  prow/job/job.py
Labels: jira/valid-reference, approved

#105 OCPQE-17601: add supports for ppc64le, multi platforms
  prow/job/__init__.py
  prow/job/job.py
Labels: jira/valid-reference
