Repository openshift/release-tests, pull requests merged in 2024-07, with the labels that each got.

#208 OCPQE-23403 support nightly upgrade testing with upgrade-from-stable build
  prow/job/controller.py
Labels: lgtm, approved

#209 correct parameter type
  oar/core/advisory_mgr.py
  oar/core/worksheet_mgr.py
Labels: lgtm, approved

#213 Check current build file exists or not
  prow/job/controller.py
Labels: lgtm, approved

#214 remove record file creation when getting latest build
  prow/job/controller.py
Labels: lgtm, approved

#216 refine cmd take-ownership
  oar/cli/cmd_take_ownership.py
  oar/core/jira_mgr.py
Labels: lgtm, approved

#218 add tomasdavidorg to reviewers section
  OWNERS
Labels: lgtm, approved

#220 Add LuboTerifaj to reviewers section
  OWNERS
Labels: lgtm, approved

#225 rename release bot logger
  tools/slack_message_receiver.py
Labels: lgtm, approved

#219 Add jhuttana to reviewers section
  OWNERS
Labels: lgtm, needs-ok-to-test, approved

#227 Add barboras7 to reviewers
  OWNERS
Labels: lgtm, approved

#229 OCPQE-23403 correct job name check logic
  prow/job/controller.py
Labels: lgtm, approved

#230 refine bugzilla login cmd
  oar/README.md
Labels: lgtm, approved

#234 OCPQE-24160 check file signature-1 instead of dir on mirror.openshift.com
  oar/cli/cmd_image_signed_check.py
Labels: lgtm, approved

#235 Add aws DR tests to release job
  _releases/ocp-4.16-test-jobs-amd64.json
Labels: lgtm, approved

#236 Support arm64 platform release jobs
  _releases/ocp-4.16-test-jobs-arm64.json
Labels: lgtm, approved

#241 OCPQE-24207 don't specify env var RELEASE_IMAGE_LATEST for arm nightly
  prow/job/job.py
Labels: lgtm, approved

#242 transform email id that contains special chars
  oar/core/notification_mgr.py
Labels: lgtm, approved

#244 OCPQE-24321 check secalert for RHSA advisory
  oar/core/advisory_mgr.py
  tests/test_advisory_mgr.py
Labels: approved
