Repository openshift/release-tests, pull requests merged in 2025-01, with the labels that each got.

#393 OCPERT-8 Add test job registry config for 4.17
  _releases/ocp-4.17-test-jobs-amd64.json
Labels: lgtm, approved

#394 OCPERT-6: Enable 4.17 release in Test Results Dashboard
  tools/auto_release_test_dashboard.py
Labels: lgtm, jira/valid-reference, approved

#409 OCPERT-43 revert auto formatted code made by black formatter on runtime py3.12
  prow/job/controller.py
  prow/job/job.py
Labels: lgtm, approved

#410 OCPERT-43 add missed line
  prow/job/controller.py
Labels: lgtm, approved

#411 Update base image to py3.12-alpine
  prow/Dockerfile
Labels: lgtm
